version: "3.9"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
